version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network
    ports:
      - "5432:5432"
    container_name: localhost
    env_file: # Загружаем переменные из .env файла
      - .env
    restart: always  # Добавляем параметр для авто-перезапуска контейнера

  picnic_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile_picnic_bot
    env_file:  # Загружаем переменные из .env файла
      - .env
    depends_on:
      - postgres
    networks:
      - bot-network
    ports:
      - "8000:8000"  # Настроить, если нужен доступ к боту через внешний порт
    restart: always  # Добавляем параметр для авто-перезапуска контейнера

  admin_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile_admin_bot
    env_file:  # Загружаем переменные из .env файла
      - .env
    depends_on:
      - postgres
    networks:
      - bot-network
    ports:
      - "8001:8001"  # Настроить, если нужен доступ к admin_bot через внешний порт
    restart: always  # Добавляем параметр для авто-перезапуска контейнера

  # Flask сервер для обработки Stripe платежей
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile_flask  # Создай Dockerfile для Flask-сервера
    env_file:  # Загружаем переменные из .env файла
      - .env
    networks:
      - bot-network
    ports:
      - "5000:5000"  # Порт для Flask-сервера
    depends_on:
      - postgres  # Убедись, что сервер поднимается после PostgreSQL
    restart: always  # Автоматический перезапуск

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
