RUN pip install --no-cache-dir -r requirements.txtRUN pip install --no-cache-dir -r requirements.txtRUN pip install --no-cache-dir -r requirements.txt# Используем Python-образ
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем необходимые файлы в контейнер
COPY requirements.txt requirements.txt
COPY . .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем приложение
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "payment_handler:app"]
